/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;

import Beans.Products;
import Model.DBConnection;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class AdminProductsScreen extends javax.swing.JPanel {
    private DBConnection dbConnection = null;
    protected static DefaultTableModel dtm;
    private ArrayList<Products> products;

    /**
     * Creates new form ProductsScreen
     */
    public AdminProductsScreen() {
        initComponents();
        dbConnection = new DBConnection();
        dtm = (DefaultTableModel) adminProductTable.getModel();
        
        //use ancestor listener to give searchbar focus
        addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                productSearchField.requestFocus();
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
        
        products = dbConnection.getAllProducts();
        populateProductTable(products);
        
    }
    
    
    //method to populate the staff sales table
    protected static void populateProductTable(ArrayList<Products> products){
        for(int index = 0; index < products.size(); index++){
            
            int productID = products.get(index).getProductID();
            String barcode = products.get(index).getBarcode();
            String category = products.get(index).getCategory();
            String name = products.get(index).getName();
            double costPrice = products.get(index).getCostPrice();
            int quantity = products.get(index).getQuantity();
            Date purchaseDate = products.get(index).getDate();
            String description = products.get(index).getDescription();
            String purchasedFrom = products.get(index).getPurchasedFrom();
            String image = products.get(index).getImage();
            
            insertIntoAdminProductTable(productID +"", barcode, category, name, costPrice +"", quantity +"", purchaseDate.toString(), description, purchasedFrom);
        }
    }
    
    //populate staff sales table
    protected static void insertIntoAdminProductTable(String productID, String barcode, String category, String name, String costPrice, String quantity, String purchaseDate, String description, String purchasedFrom){
        String[] rowData = {productID, barcode, category, name, costPrice, quantity, purchaseDate, description, purchasedFrom};
        dtm.addRow(rowData);
    }
    
    //get details of selected product from table
    public Products getSelectedProductDetail(){
            int productID = Integer.parseInt(adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 0).toString());
            String barcode = adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 1).toString();
            String category = adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 2).toString();
            String name = adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 3).toString();
            double costPrice = Double.parseDouble(adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 4).toString());
            int quantity = Integer.parseInt(adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 5).toString());
            Date purchaseDate = Date.valueOf(adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 6).toString());
            String description = adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 7).toString();
            String purchasedFrom = adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 8).toString();
            String image = dbConnection.getProductImagePath(productID);

            Products products = new Products(productID, barcode, category, name, costPrice, quantity, purchaseDate, description, purchasedFrom, image);
            
            return  products;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productSearchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminProductTable = new javax.swing.JTable();
        addNewProductLabel = new javax.swing.JLabel();
        editSelectedProductButton = new javax.swing.JLabel();
        removeSelectedProduct = new javax.swing.JLabel();
        productSortBy = new javax.swing.JComboBox<>();
        searchByComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 29));
        setPreferredSize(new java.awt.Dimension(1080, 615));

        productSearchField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productSearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                productSearchFieldKeyTyped(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(51, 51, 0));
        searchButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search-32.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 102, 102));
        refreshButton.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/up.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        adminProductTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Barcode", "Category", "Name", "Cost Price", "Quantity", "Purchase Date", "Description", "Purchased From"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminProductTable);
        if (adminProductTable.getColumnModel().getColumnCount() > 0) {
            adminProductTable.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        addNewProductLabel.setBackground(new java.awt.Color(0, 51, 0));
        addNewProductLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        addNewProductLabel.setForeground(new java.awt.Color(255, 255, 255));
        addNewProductLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addNewProductLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/07_plus-20.png"))); // NOI18N
        addNewProductLabel.setText("Add New Product");
        addNewProductLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addNewProductLabel.setOpaque(true);
        addNewProductLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewProductLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addNewProductLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNewProductLabelMouseExited(evt);
            }
        });

        editSelectedProductButton.setBackground(new java.awt.Color(0, 102, 102));
        editSelectedProductButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        editSelectedProductButton.setForeground(new java.awt.Color(255, 255, 255));
        editSelectedProductButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editSelectedProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_file_16px.png"))); // NOI18N
        editSelectedProductButton.setText("Edit Selected Product");
        editSelectedProductButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editSelectedProductButton.setOpaque(true);
        editSelectedProductButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSelectedProductButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editSelectedProductButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editSelectedProductButtonMouseExited(evt);
            }
        });

        removeSelectedProduct.setBackground(new java.awt.Color(153, 0, 0));
        removeSelectedProduct.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        removeSelectedProduct.setForeground(new java.awt.Color(255, 255, 255));
        removeSelectedProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeSelectedProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/del.png"))); // NOI18N
        removeSelectedProduct.setText("Remove Selected Product");
        removeSelectedProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        removeSelectedProduct.setOpaque(true);
        removeSelectedProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeSelectedProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeSelectedProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeSelectedProductMouseExited(evt);
            }
        });

        productSortBy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        productSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product ID", "Product Name" }));
        productSortBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productSortByActionPerformed(evt);
            }
        });

        searchByComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Product Barcode", "Product Name" }));
        searchByComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search By:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sort By:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334)
                .addComponent(searchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(productSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266)
                .addComponent(productSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(addNewProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(editSelectedProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(removeSelectedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(productSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addNewProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(editSelectedProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeSelectedProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editSelectedProductButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSelectedProductButtonMouseClicked
        if(adminProductTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "No product selected.", "message", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            EditProduct.product = getSelectedProductDetail();
            new EditProduct(null, true).setVisible(true);
        }
        
    }//GEN-LAST:event_editSelectedProductButtonMouseClicked

    private void addNewProductLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewProductLabelMouseEntered
        addNewProductLabel.setBackground(new Color(0,75,6));
    }//GEN-LAST:event_addNewProductLabelMouseEntered

    private void addNewProductLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewProductLabelMouseExited
        addNewProductLabel.setBackground(new Color(0,51,0));
    }//GEN-LAST:event_addNewProductLabelMouseExited

    private void editSelectedProductButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSelectedProductButtonMouseEntered
        editSelectedProductButton.setBackground(new Color(0, 124, 105));
    }//GEN-LAST:event_editSelectedProductButtonMouseEntered

    private void editSelectedProductButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSelectedProductButtonMouseExited
        editSelectedProductButton.setBackground(new Color(0,102,102));
    }//GEN-LAST:event_editSelectedProductButtonMouseExited

    private void removeSelectedProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSelectedProductMouseEntered
        removeSelectedProduct.setBackground(new Color(189, 0, 0));
    }//GEN-LAST:event_removeSelectedProductMouseEntered

    private void removeSelectedProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSelectedProductMouseExited
        removeSelectedProduct.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_removeSelectedProductMouseExited

    private void addNewProductLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewProductLabelMouseClicked
        new AddNewProduct(null, true).setVisible(true);
    }//GEN-LAST:event_addNewProductLabelMouseClicked

    private void removeSelectedProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeSelectedProductMouseClicked
        if(adminProductTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "No product selected.", "message", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int deleteOption = JOptionPane.showConfirmDialog(this, "Do You Really Want To Delete This Product", "Delete Product", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(deleteOption == JOptionPane.YES_OPTION){
                int productID = Integer.parseInt(adminProductTable.getValueAt(adminProductTable.getSelectedRow(), 0).toString());
                dbConnection.deleteProduct(productID);
                
                dtm.setRowCount(0);
                products = dbConnection.getAllProducts();
                populateProductTable(products);
                JOptionPane.showMessageDialog(this, "Product Successfully Deleted.", "Message",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_removeSelectedProductMouseClicked

    private void searchByComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByComboBoxActionPerformed
        if(searchByComboBox.getSelectedIndex() == 0){
            productSearchField.setText("");
        }
    }//GEN-LAST:event_searchByComboBoxActionPerformed

    private void adminProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminProductTableMouseClicked
        
        if(evt.getClickCount() == 2){
            
            DisplaySelectedProduct.products = getSelectedProductDetail();
            new DisplaySelectedProduct(null, true).setVisible(true);
            
        }
        
    }//GEN-LAST:event_adminProductTableMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        dtm.setRowCount(0);
        products = dbConnection.getAllProducts();
        populateProductTable(products);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void productSearchFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productSearchFieldKeyTyped
        if(searchByComboBox.getSelectedIndex() == 0){
            if(evt.getKeyChar() == 10){
                String barcode = productSearchField.getText();
                
                products = dbConnection.getProductUsingBarcode(barcode);
                if(products.isEmpty()){
                    JOptionPane.showMessageDialog(this, "No product with such BARCODE.", "message", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    dtm.setRowCount(0);
                    populateProductTable(products);
                    productSearchField.setText("");
                }
                
            }
        }
//        else if(searchByComboBox.getSelectedIndex() == 1){
//            
//        }
    }//GEN-LAST:event_productSearchFieldKeyTyped

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (productSearchField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Search cannot be empty!", "message", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            if (searchByComboBox.getSelectedIndex() == 0) {
                String barcode = productSearchField.getText().trim();

                products = dbConnection.getProductUsingBarcode(barcode);
                if(products.isEmpty()){
                    JOptionPane.showMessageDialog(this, "No product with such BARCODE.", "message", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    dtm.setRowCount(0);
                    populateProductTable(products);
                }

            }
            else if (searchByComboBox.getSelectedIndex() == 1) {
                String productName = productSearchField.getText().trim();

                products = dbConnection.getProductUsingProductName(productName);
                if(products.isEmpty()){
                    JOptionPane.showMessageDialog(this, "No product with such NAME.", "message", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    dtm.setRowCount(0);
                    populateProductTable(products);
                }
            }
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void productSortByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productSortByActionPerformed
        if(productSortBy.getSelectedIndex() == 0){
            products = dbConnection.getAllProducts();
            dtm.setRowCount(0);
            populateProductTable(products);
        }
        else if(productSortBy.getSelectedIndex() == 1){
            products = dbConnection.getAllProductsByName();
            dtm.setRowCount(0);
            populateProductTable(products);
        }
    }//GEN-LAST:event_productSortByActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewProductLabel;
    private javax.swing.JTable adminProductTable;
    private javax.swing.JLabel editSelectedProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productSearchField;
    private javax.swing.JComboBox<String> productSortBy;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel removeSelectedProduct;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchByComboBox;
    // End of variables declaration//GEN-END:variables
}
