/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;

import Beans.Staff;
import Model.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class AdminLogin extends javax.swing.JFrame {
    private DBConnection dbConnection = null;
    private MainScreen mainScreen;
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
        this.setLocation(300,100);
        dbConnection = new DBConnection();
        
//        mainScreen = new MainScreen();
        wrongDetails.setVisible(false);
    }
    
    //a method to check for empty fields
    public Boolean isFieldEmpty(){
        boolean isEmpty = false;
        
        if(usernameField.getText().isEmpty() || passwordField.getText().isEmpty()){
            isEmpty = true;
        }
        
        return isEmpty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffLoginUsername1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        adminLoginBackButton = new javax.swing.JButton();
        adminLoginButton = new javax.swing.JButton();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        wrongDetails = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 435));

        jPanel1.setLayout(null);

        staffLoginUsername1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        staffLoginUsername1.setForeground(new java.awt.Color(255, 255, 255));
        staffLoginUsername1.setText("Username:");
        jPanel1.add(staffLoginUsername1);
        staffLoginUsername1.setBounds(60, 120, 130, 27);

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFieldMouseClicked(evt);
            }
        });
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });
        jPanel1.add(usernameField);
        usernameField.setBounds(230, 120, 280, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 200, 130, 27);

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        jPanel1.add(passwordField);
        passwordField.setBounds(230, 200, 280, 30);

        adminLoginBackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminLoginBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        adminLoginBackButton.setText("Back");
        adminLoginBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBackButtonActionPerformed(evt);
            }
        });
        adminLoginBackButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminLoginBackButtonKeyPressed(evt);
            }
        });
        jPanel1.add(adminLoginBackButton);
        adminLoginBackButton.setBounds(240, 310, 130, 40);

        adminLoginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/alogin.png"))); // NOI18N
        adminLoginButton.setText("Login");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });
        adminLoginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adminLoginButtonKeyPressed(evt);
            }
        });
        jPanel1.add(adminLoginButton);
        adminLoginButton.setBounds(380, 310, 130, 40);

        showPasswordCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordCheckBox.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        showPasswordCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(showPasswordCheckBox);
        showPasswordCheckBox.setBounds(380, 240, 130, 23);

        wrongDetails.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        wrongDetails.setForeground(new java.awt.Color(255, 0, 0));
        wrongDetails.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wrongDetails.setText("userame or password incorrect");
        jPanel1.add(wrongDetails);
        wrongDetails.setBounds(310, 270, 200, 20);

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ADMIN Login");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 30, 650, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 430);

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ADMIN Login");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 30, 300, 38);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed

    }//GEN-LAST:event_passwordFieldKeyPressed

    private void adminLoginBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBackButtonActionPerformed
        dispose();
        new WelcomeScreen().setVisible(true);
    }//GEN-LAST:event_adminLoginBackButtonActionPerformed

    private void adminLoginBackButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminLoginBackButtonKeyPressed

    }//GEN-LAST:event_adminLoginBackButtonKeyPressed

    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        if (isFieldEmpty().equals(true)) {
            JOptionPane.showMessageDialog(this, "One Or More Fields Are Empty.", "Message", JOptionPane.WARNING_MESSAGE);
        } else {
            String username = usernameField.getText();
            String password = passwordField.getText();
            Staff staff  = dbConnection.verifyAdminLogin(username, password);
            
            if(staff != null){
                dispose();
                MainScreen.staff = staff;
                new MainScreen().setVisible(true);
            }
            else{
                wrongDetails.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void adminLoginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminLoginButtonKeyPressed

    }//GEN-LAST:event_adminLoginButtonKeyPressed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if(showPasswordCheckBox.isSelected()){
            passwordField.setEchoChar((char)0);
        }
        else{
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void usernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseClicked
        if(wrongDetails.isVisible() == true){
            wrongDetails.setVisible(false);
        }
    }//GEN-LAST:event_usernameFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if(wrongDetails.isVisible() == true){
            wrongDetails.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginBackButton;
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JLabel staffLoginUsername1;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel wrongDetails;
    // End of variables declaration//GEN-END:variables
}
