/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;

import Beans.Products;
import Model.DBConnection;
import Utils.SizeImage;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class AdminHome extends javax.swing.JPanel {
    private DBConnection dbConnection = null;
    protected static DefaultTableModel dtm;
    private ArrayList<Products> products;

    /**
     * Creates new form ProductsScreen
     */
    public AdminHome() {
        initComponents();
        
        SizeImage.sizeImageToLabelSize(logoLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 29));
        setPreferredSize(new java.awt.Dimension(1080, 615));
        setLayout(null);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sis.png"))); // NOI18N
        add(logoLabel);
        logoLabel.setBounds(268, 169, 503, 365);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 194, 74));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome to Admin DashBoard!  ");
        add(jLabel3);
        jLabel3.setBounds(0, 28, 1070, 76);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logoLabel;
    // End of variables declaration//GEN-END:variables
}
