/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;

import Beans.Category;
import Beans.Customer;
import Model.DBConnection;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class CustomerScreen extends javax.swing.JPanel {

    private DBConnection dbConnection = null;
    protected static DefaultTableModel dtm;
    private ArrayList<Customer> customers;

    /**
     * Creates new form ProductsScreen
     */
    public CustomerScreen() {
        initComponents();
        dbConnection = new DBConnection();
        dtm = (DefaultTableModel) customerDetailsTable.getModel();

        customers = dbConnection.getAllCustomersDetails();
        populateCustomerTable(customers);

        //clear fields 
        clearDisplayLabels();
        EditCustomer.customerScreen = this;     //pass this customer screen to edit customer
    }

    //method to populate the customer table
    protected static void populateCustomerTable(ArrayList<Customer> customers) {
        for (int index = 0; index < customers.size(); index++) {

            int customerID = customers.get(index).getCustomerID();
            String firstName = customers.get(index).getCustomerFirstName();
            String lastname = customers.get(index).getCustomerLastName();
            String phone = customers.get(index).getCustomerPhone();
            String email = customers.get(index).getCustomerEmail();
            double totalPurchase = customers.get(index).getTotalPurchase();

            insertIntoCustomerTable(customerID, firstName, lastname, phone, email, totalPurchase);
        }
    }

    //populate customer table
    protected static void insertIntoCustomerTable(int customerID, String customerFirstName, String customerLastName, String customerPhone, String customerEmail, double totalPurchase) {
        String[] rowData = {customerID + "", customerFirstName, customerLastName, customerPhone, customerEmail, totalPurchase + ""};
        dtm.addRow(rowData);
    }

    //clear labels
    public void clearDisplayLabels() {
        idField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        telField.setText("");
        emailField.setText("");

        ordersCountLabel.setText("###");
        totalOrdersAmountLabel.setText("###");
        lastOrderDateLabel.setText("###");
    }
    
    //get details of selected customer from table
    public Customer getSelectedCustomerDetail(){
            int customerID = Integer.parseInt(customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 0).toString());
            String firstName = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 1).toString();
            String lastName = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 2).toString();
            String tel = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 3).toString();
            String email = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 4).toString();

            Customer customer = new Customer(customerID, firstName, lastName, tel, email);
            
            return  customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerDetailsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        removeCustomerButton = new javax.swing.JButton();
        editCustomerButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ordersCountLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        totalOrdersAmountLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lastOrderDateLabel = new javax.swing.JLabel();
        customerSort = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 51, 51));
        setPreferredSize(new java.awt.Dimension(1080, 615));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID:");
        add(jLabel1);
        jLabel1.setBounds(10, 126, 116, 38);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name:");
        add(jLabel2);
        jLabel2.setBounds(10, 171, 116, 38);

        idField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idField.setEnabled(false);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        add(idField);
        idField.setBounds(144, 127, 80, 38);

        firstNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        firstNameField.setEnabled(false);
        add(firstNameField);
        firstNameField.setBounds(144, 171, 182, 38);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        customerDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Tel", "Email", "Total Purchase"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerDetailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerDetailsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerDetailsTable);
        if (customerDetailsTable.getColumnModel().getColumnCount() > 0) {
            customerDetailsTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            customerDetailsTable.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(344, 53, 738, 359);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Last Name:");
        add(jLabel4);
        jLabel4.setBounds(10, 215, 116, 38);

        lastNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lastNameField.setEnabled(false);
        add(lastNameField);
        lastNameField.setBounds(144, 216, 182, 38);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tel:");
        add(jLabel5);
        jLabel5.setBounds(10, 260, 116, 38);

        telField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telField.setEnabled(false);
        add(telField);
        telField.setBounds(144, 260, 182, 38);

        emailField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailField.setEnabled(false);
        add(emailField);
        emailField.setBounds(144, 304, 182, 38);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email:");
        add(jLabel6);
        jLabel6.setBounds(10, 304, 116, 38);

        removeCustomerButton.setBackground(new java.awt.Color(0, 102, 255));
        removeCustomerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        removeCustomerButton.setText("Remove");
        removeCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCustomerButtonActionPerformed(evt);
            }
        });
        add(removeCustomerButton);
        removeCustomerButton.setBounds(911, 413, 163, 43);

        editCustomerButton.setBackground(new java.awt.Color(0, 0, 102));
        editCustomerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        editCustomerButton.setText("Edit");
        editCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerButtonActionPerformed(evt);
            }
        });
        add(editCustomerButton);
        editCustomerButton.setBounds(762, 413, 139, 43);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Summary", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Orders Count:");

        ordersCountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordersCountLabel.setForeground(new java.awt.Color(255, 255, 255));
        ordersCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordersCountLabel.setText("5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(ordersCountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ordersCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Total Orders Amount:");

        totalOrdersAmountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalOrdersAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalOrdersAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalOrdersAmountLabel.setText("12,500.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(totalOrdersAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalOrdersAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 51, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Last Orders Date:");

        lastOrderDateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lastOrderDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastOrderDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastOrderDateLabel.setText("14/01/2020");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lastOrderDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastOrderDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        add(jPanel1);
        jPanel1.setBounds(423, 474, 659, 130);

        customerSort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Total Purchase" }));
        customerSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerSortActionPerformed(evt);
            }
        });
        add(customerSort);
        customerSort.setBounds(939, 16, 143, 26);
    }// </editor-fold>//GEN-END:initComponents

    private void removeCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCustomerButtonActionPerformed
        if(customerDetailsTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "No customer selected.", "message", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int deleteOption = JOptionPane.showConfirmDialog(this, "Do You Really Want To Delete This Customer", "Delete Customer", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if(deleteOption == JOptionPane.YES_OPTION){
                int CustomerID = Integer.parseInt(customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 0).toString());
                dbConnection.deleteCustomer(CustomerID);
                
                dtm.setRowCount(0);
                customers = dbConnection.getAllCustomersDetails();
                populateCustomerTable(customers);
                clearDisplayLabels();   //clear fields 
                JOptionPane.showMessageDialog(this, "Customer Successfully Deleted.", "Message",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_removeCustomerButtonActionPerformed

    private void editCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerButtonActionPerformed
        if(customerDetailsTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "No customer selected.", "message", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            EditCustomer.customer = getSelectedCustomerDetail();
            new EditCustomer(null, true).setVisible(true);
        }
        
    }//GEN-LAST:event_editCustomerButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void customerDetailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDetailsTableMouseClicked

        //get the selected customer details
        int customerID = Integer.parseInt(customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 0).toString());
        String firstName = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 1).toString();
        String lastName = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 2).toString();
        String tel = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 3).toString();
        String email = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 4).toString();
        String totalPurchase = customerDetailsTable.getValueAt(customerDetailsTable.getSelectedRow(), 5).toString();

        //display details on display fields
        idField.setText(customerID +"");
        firstNameField.setText(firstName);
        lastNameField.setText(lastName);
        telField.setText(tel);
        emailField.setText(email);

        ArrayList<String> purchaseDetails = dbConnection.getLastPurchaseDate_Count(customerID);
        
        lastOrderDateLabel.setText(purchaseDetails.get(0));
        ordersCountLabel.setText(purchaseDetails.get(1));
        totalOrdersAmountLabel.setText(totalPurchase);

    }//GEN-LAST:event_customerDetailsTableMouseClicked

    private void customerSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerSortActionPerformed
        if(customerSort.getSelectedIndex() == 0){
            customers = dbConnection.getAllCustomersDetails();
            dtm.setRowCount(0);
            populateCustomerTable(customers);
            
            clearDisplayLabels();   //clear fields s
        }
        else if(customerSort.getSelectedIndex() == 1){
            customers = dbConnection.getAllCustomersOrderByName();
            dtm.setRowCount(0);
            populateCustomerTable(customers);
            
            clearDisplayLabels();   //clear fields 
        }
        else if(customerSort.getSelectedIndex() == 2){
            customers = dbConnection.getAllCustomersOrderByHighestPurchase();
            dtm.setRowCount(0);
            populateCustomerTable(customers);
            
            clearDisplayLabels();   //clear fields 
        }
    }//GEN-LAST:event_customerSortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerDetailsTable;
    private javax.swing.JComboBox<String> customerSort;
    private javax.swing.JButton editCustomerButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastOrderDateLabel;
    private javax.swing.JLabel ordersCountLabel;
    private javax.swing.JButton removeCustomerButton;
    private javax.swing.JTextField telField;
    private javax.swing.JLabel totalOrdersAmountLabel;
    // End of variables declaration//GEN-END:variables
}
