/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;
import Beans.Staff;
import Model.DBConnection;
import Utils.SizeImage;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class MainScreen extends javax.swing.JFrame {
    private DBConnection dbConnection = null;
    
    protected static JLabel adminLabel;
    protected static Staff staff;
    
    
    StaffProductsScreen product = new StaffProductsScreen();
    CategoryScreen category = new CategoryScreen();
    CustomerScreen student = new CustomerScreen();
    SalesScreen order = new SalesScreen();
    AdminDashboard adminDashboard = new AdminDashboard();

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        dbConnection = new DBConnection();
        adminLabel = adminPanelLabel;    //instance of adminDashboard label to aid visibility during admin/staff login
        
        SizeImage.sizeImageToLabelSize(mainScreenBackgroundImageLabel);   //set background image to match background panel
        addPanelsToMainScreenContentPanel();    //add panels for display
//        sizeImageToLabelSize(sekaroLabel); 

        //Set user details on login
        if(staff != null){
            userNameLabel.setText(staff.getFirstName() +" "+ staff.getLastName());
            userTypeLabel.setText("(" + staff.getStatus()+ ")");
            String department = dbConnection.getDepartmentByID(Integer.parseInt(staff.getDepartment()));
            userDeptLabel.setText("Dept: " + department);
        }
    }
    
    
//    //method to size up background image to label's size
//    public static void sizeImageToLabelSize(JLabel containerLabel){
//        int width = containerLabel.getWidth();
//        int height = containerLabel.getHeight();
//        
//        ImageIcon originalIcon = (ImageIcon) containerLabel.getIcon();
//        Image img = originalIcon.getImage();
//        Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
//        ImageIcon original = new ImageIcon(scaledImg);
//        containerLabel.setIcon(original);
//    }
    
    //method to add panels for display
    public void addPanelsToMainScreenContentPanel(){
        mainScreenContentPanel.add(product);
        mainScreenContentPanel.add(category);
        mainScreenContentPanel.add(student);
        mainScreenContentPanel.add(order);
        mainScreenContentPanel.add(adminDashboard);
    }

    //method to clear all visible panels on home screen
    public void changePanelsVisibilityOnHomeScreen(){
        for(Component component : this.mainScreenContentPanel.getComponents()){
            component.setVisible(false);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScreenMainPanel = new javax.swing.JPanel();
        mainScreenHeaderPanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        adminPanelLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        profileImage = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userDeptLabel = new javax.swing.JLabel();
        userTypeLabel = new javax.swing.JLabel();
        mainScreenContentPanel = new javax.swing.JPanel();
        mainScreenHeader = new javax.swing.JLabel();
        mainScreenBackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1370, 770));
        setResizable(false);

        mainScreenHeaderPanel.setBackground(new java.awt.Color(51, 153, 255));
        mainScreenHeaderPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        mainScreenHeaderPanel.setLayout(null);

        homeLabel.setBackground(new java.awt.Color(255, 153, 51));
        homeLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_24px.png"))); // NOI18N
        homeLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(255, 51, 0)));
        homeLabel.setOpaque(true);
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLabelMouseExited(evt);
            }
        });
        mainScreenHeaderPanel.add(homeLabel);
        homeLabel.setBounds(0, 0, 90, 70);

        productLabel.setBackground(new java.awt.Color(255, 153, 51));
        productLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        productLabel.setForeground(new java.awt.Color(255, 255, 255));
        productLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productLabel.setText("        PRODUCTS     |");
        productLabel.setOpaque(true);
        productLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productLabelMouseExited(evt);
            }
        });
        mainScreenHeaderPanel.add(productLabel);
        productLabel.setBounds(90, 0, 166, 70);

        orderLabel.setBackground(new java.awt.Color(255, 153, 51));
        orderLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        orderLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderLabel.setText("       ORDER      ");
        orderLabel.setOpaque(true);
        orderLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderLabelMouseExited(evt);
            }
        });
        mainScreenHeaderPanel.add(orderLabel);
        orderLabel.setBounds(250, 0, 123, 70);

        adminPanelLabel.setBackground(new java.awt.Color(255, 153, 51));
        adminPanelLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        adminPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminPanelLabel.setText("|        ADMIN     ");
        adminPanelLabel.setOpaque(true);
        adminPanelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPanelLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminPanelLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminPanelLabelMouseExited(evt);
            }
        });
        mainScreenHeaderPanel.add(adminPanelLabel);
        adminPanelLabel.setBounds(370, 0, 132, 70);

        logoutButton.setBackground(new java.awt.Color(51, 153, 255));
        logoutButton.setFont(new java.awt.Font("KBZipaDeeDooDah", 0, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.setContentAreaFilled(false);
        logoutButton.setOpaque(true);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        mainScreenHeaderPanel.add(logoutButton);
        logoutButton.setBounds(1200, 0, 150, 62);

        profileImage.setBackground(new java.awt.Color(51, 153, 255));
        profileImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        profileImage.setToolTipText("View Profile");
        profileImage.setOpaque(true);
        profileImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileImageMouseExited(evt);
            }
        });
        mainScreenHeaderPanel.add(profileImage);
        profileImage.setBounds(1160, 20, 30, 30);

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userNameLabel.setText("Miracle Awajioyem");
        userNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userNameLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userNameLabelMouseExited(evt);
            }
        });
        mainScreenHeaderPanel.add(userNameLabel);
        userNameLabel.setBounds(870, 20, 280, 20);

        userDeptLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userDeptLabel.setForeground(new java.awt.Color(153, 255, 51));
        userDeptLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userDeptLabel.setText("Dept: Sales");
        mainScreenHeaderPanel.add(userDeptLabel);
        userDeptLabel.setBounds(950, 40, 200, 15);

        userTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userTypeLabel.setForeground(new java.awt.Color(153, 255, 51));
        userTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userTypeLabel.setText("(Staff)");
        mainScreenHeaderPanel.add(userTypeLabel);
        userTypeLabel.setBounds(1010, 10, 140, 10);

        mainScreenHeader.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        mainScreenHeader.setForeground(new java.awt.Color(255, 255, 255));
        mainScreenHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainScreenHeader.setText("SEKARO INVENTORY MANAGEMENT SYSYTEM");

        mainScreenBackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Kids-running-in-schoolyard-1500-x-1000.jpg"))); // NOI18N

        javax.swing.GroupLayout mainScreenContentPanelLayout = new javax.swing.GroupLayout(mainScreenContentPanel);
        mainScreenContentPanel.setLayout(mainScreenContentPanelLayout);
        mainScreenContentPanelLayout.setHorizontalGroup(
            mainScreenContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScreenBackgroundImageLabel)
            .addComponent(mainScreenHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        mainScreenContentPanelLayout.setVerticalGroup(
            mainScreenContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScreenBackgroundImageLabel)
            .addGroup(mainScreenContentPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(mainScreenHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout mainScreenMainPanelLayout = new javax.swing.GroupLayout(mainScreenMainPanel);
        mainScreenMainPanel.setLayout(mainScreenMainPanelLayout);
        mainScreenMainPanelLayout.setHorizontalGroup(
            mainScreenMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScreenHeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainScreenContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainScreenMainPanelLayout.setVerticalGroup(
            mainScreenMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainScreenMainPanelLayout.createSequentialGroup()
                .addComponent(mainScreenHeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainScreenContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScreenMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainScreenMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int closeOption = JOptionPane.showConfirmDialog(this, "Do You Really Want To LOGOUT?", "Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(closeOption == JOptionPane.YES_OPTION){
            dispose();
            
            //Clear off logged in user details
            userNameLabel.setText("");
            userTypeLabel.setText("");
            userDeptLabel.setText("");
            
            new WelcomeScreen().setVisible(true);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void productLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLabelMouseClicked
        changePanelsVisibilityOnHomeScreen();
        
        product.updateProductTable();
        product.setSize(mainScreenContentPanel.getSize());
        product.setVisible(true);
    }//GEN-LAST:event_productLabelMouseClicked

    private void productLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLabelMouseEntered
        productLabel.setBackground(new Color(255, 117, 52));
    }//GEN-LAST:event_productLabelMouseEntered

    private void productLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productLabelMouseExited
        productLabel.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_productLabelMouseExited

    private void orderLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLabelMouseEntered
        orderLabel.setBackground(new Color(255, 117, 52));
    }//GEN-LAST:event_orderLabelMouseEntered

    private void orderLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLabelMouseExited
        orderLabel.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_orderLabelMouseExited

    private void adminPanelLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelLabelMouseEntered
        adminPanelLabel.setBackground(new Color(255, 117, 52));
    }//GEN-LAST:event_adminPanelLabelMouseEntered

    private void adminPanelLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelLabelMouseExited
        adminPanelLabel.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_adminPanelLabelMouseExited

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        logoutButton.setBackground(new Color(51,208,255));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        logoutButton.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void orderLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLabelMouseClicked
        SalesScreen.staff = staff;
        changePanelsVisibilityOnHomeScreen();
        
        order.setSize(mainScreenContentPanel.getSize());
        order.setVisible(true);
    }//GEN-LAST:event_orderLabelMouseClicked

    private void homeLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseEntered
        homeLabel.setBackground(new Color(255, 117, 52));
    }//GEN-LAST:event_homeLabelMouseEntered

    private void homeLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseExited
        homeLabel.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_homeLabelMouseExited

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        changePanelsVisibilityOnHomeScreen();
        mainScreenBackgroundImageLabel.setVisible(true);
    }//GEN-LAST:event_homeLabelMouseClicked

    private void adminPanelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPanelLabelMouseClicked
        changePanelsVisibilityOnHomeScreen();
        adminDashboard.setSize(mainScreenContentPanel.getSize());
        adminDashboard.setVisible(true);
        
        JPanel panel = AdminDashboard.display;
        for(Component component : panel.getComponents()){
            component.setVisible(false);
        }
        
        AdminHome adminHome = new AdminHome();
        adminHome.setSize(panel.getSize());
        panel.add(adminHome);
        adminHome.setVisible(true);
    }//GEN-LAST:event_adminPanelLabelMouseClicked

    private void profileImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImageMouseEntered
        profileImage.setBackground(new Color(51,212,255));
    }//GEN-LAST:event_profileImageMouseEntered

    private void profileImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImageMouseExited
        profileImage.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_profileImageMouseExited

    private void profileImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImageMouseClicked
        StaffProfile.staff = staff;     //pass logged in staff object to StaffProfile class
        new StaffProfile(null, true).setVisible(true);
    }//GEN-LAST:event_profileImageMouseClicked

    private void userNameLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameLabelMouseEntered
        userNameLabel.setForeground(new Color(255,153,51));
    }//GEN-LAST:event_userNameLabelMouseEntered

    private void userNameLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameLabelMouseExited
        userNameLabel.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_userNameLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminPanelLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mainScreenBackgroundImageLabel;
    private javax.swing.JPanel mainScreenContentPanel;
    private javax.swing.JLabel mainScreenHeader;
    private javax.swing.JPanel mainScreenHeaderPanel;
    private javax.swing.JPanel mainScreenMainPanel;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel productLabel;
    private javax.swing.JLabel profileImage;
    private javax.swing.JLabel userDeptLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
