/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;

import Beans.Staff;
import Model.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class StaffLogin extends javax.swing.JFrame {
    private DBConnection dbConnection = null;
//    private MainScreen mainScreen;

    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
        this.setLocation(300, 100);
        dbConnection = new DBConnection();

//        mainScreen = new MainScreen();
        wrongDetails.setVisible(false);
    }

    //a method to check for empty fields
    public Boolean isFieldEmpty() {
        boolean isEmpty = false;

        if (usernameField.getText().isEmpty() || passwordField.getText().isEmpty()) {
            isEmpty = true;
        }

        return isEmpty;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        staffLoginBackButton = new javax.swing.JButton();
        staffLoginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        staffLoginUsername1 = new javax.swing.JLabel();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        usernameField = new javax.swing.JTextField();
        wrongDetails = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(550, 435));
        setPreferredSize(new java.awt.Dimension(550, 435));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(550, 435));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STAFF Login");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 30, 300, 38);

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passwordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordFieldMouseClicked(evt);
            }
        });
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        jPanel1.add(passwordField);
        passwordField.setBounds(230, 200, 280, 30);

        staffLoginBackButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        staffLoginBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        staffLoginBackButton.setText("Back");
        staffLoginBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLoginBackButtonActionPerformed(evt);
            }
        });
        staffLoginBackButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                staffLoginBackButtonKeyPressed(evt);
            }
        });
        jPanel1.add(staffLoginBackButton);
        staffLoginBackButton.setBounds(240, 310, 130, 40);

        staffLoginButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        staffLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ulogin.png"))); // NOI18N
        staffLoginButton.setText("Login");
        staffLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffLoginButtonActionPerformed(evt);
            }
        });
        staffLoginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                staffLoginButtonKeyPressed(evt);
            }
        });
        jPanel1.add(staffLoginButton);
        staffLoginButton.setBounds(380, 310, 130, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 200, 130, 27);

        staffLoginUsername1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        staffLoginUsername1.setText("Username:");
        jPanel1.add(staffLoginUsername1);
        staffLoginUsername1.setBounds(60, 120, 130, 27);

        showPasswordCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        showPasswordCheckBox.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        showPasswordCheckBox.setForeground(new java.awt.Color(51, 51, 51));
        showPasswordCheckBox.setText("Show Password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(showPasswordCheckBox);
        showPasswordCheckBox.setBounds(380, 240, 130, 23);

        usernameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameFieldMouseClicked(evt);
            }
        });
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldKeyPressed(evt);
            }
        });
        jPanel1.add(usernameField);
        usernameField.setBounds(230, 120, 280, 30);

        wrongDetails.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        wrongDetails.setForeground(new java.awt.Color(255, 0, 0));
        wrongDetails.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wrongDetails.setText("userame or password incorrect");
        jPanel1.add(wrongDetails);
        wrongDetails.setBounds(310, 270, 200, 20);

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teacher.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(550, 435));
        jLabel2.setMinimumSize(new java.awt.Dimension(550, 435));
        jLabel2.setPreferredSize(new java.awt.Dimension(550, 435));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -5, 540, 435);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed

    }//GEN-LAST:event_passwordFieldKeyPressed

    private void staffLoginBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffLoginBackButtonActionPerformed
        dispose();
        new WelcomeScreen().setVisible(true);
    }//GEN-LAST:event_staffLoginBackButtonActionPerformed

    private void staffLoginBackButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_staffLoginBackButtonKeyPressed

    }//GEN-LAST:event_staffLoginBackButtonKeyPressed

    private void staffLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffLoginButtonActionPerformed
        if (isFieldEmpty().equals(true)) {
            JOptionPane.showMessageDialog(this, "One Or More Fields Are Empty.", "Message", JOptionPane.WARNING_MESSAGE);
        } else {
            String username = usernameField.getText();
            String password = passwordField.getText();
            Staff staff = dbConnection.verifyStaffLogin(username, password);  //staff object returned from login to set staff details on login
            
            if(staff != null){
                dispose();
                MainScreen.staff = staff;
                new MainScreen().setVisible(true);
                MainScreen.adminLabel.setVisible(false);
            }
            else{
                wrongDetails.setVisible(true);
            }
        }
    }//GEN-LAST:event_staffLoginButtonActionPerformed

    private void staffLoginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_staffLoginButtonKeyPressed

    }//GEN-LAST:event_staffLoginButtonKeyPressed

    private void usernameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldKeyPressed

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if(showPasswordCheckBox.isSelected()){
            passwordField.setEchoChar((char)0);
        }
        else{
            passwordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void usernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameFieldMouseClicked
        if(wrongDetails.isVisible() == true){
            wrongDetails.setVisible(false);
        }
    }//GEN-LAST:event_usernameFieldMouseClicked

    private void passwordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordFieldMouseClicked
        if(wrongDetails.isVisible() == true){
            wrongDetails.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JButton staffLoginBackButton;
    private javax.swing.JButton staffLoginButton;
    private javax.swing.JLabel staffLoginUsername1;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel wrongDetails;
    // End of variables declaration//GEN-END:variables
}
