/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIs;

import Beans.Staff;
import Model.DBConnection;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Nzekwe
 */
public class StaffProfile extends javax.swing.JDialog {
    private DBConnection connection = null;
    protected static Staff staff;
    UserProfilePanel profile;
    UserSalesPanel sales;
    /**
     * Creates new form EditProduct
     */
    public StaffProfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(100,20);
        connection = new DBConnection();
        
        staff = connection.getStaffByID(staff.getId());     //refresh the staff attributes' values with the recent values
        
        UserProfilePanel.staff = staff;     //pass logged in staff object to UserProfilePanel class for profile attributes
        UserSalesPanel.staff = staff;     //pass logged in staff object to UserSalesPanel class for sales display
        
        //initialising UserProfilePanel and UserSalesPanel panels
        profile = new UserProfilePanel();
        sales = new UserSalesPanel();
        
        addPanelsToMainScreenContentPanel();
        changePanelsVisibilityOnHomeScreen();
        profile.setSize(staffProfileContent.getSize());     //set UserProfilePanel as default display
        profile.setVisible(true);
        
    }
    
    //method to add panels for display
    public void addPanelsToMainScreenContentPanel(){
        staffProfileContent.add(profile);
        staffProfileContent.add(sales);
    }

    public void changePanelsVisibilityOnHomeScreen(){
        for(Component component : this.staffProfileContent.getComponents()){
            component.setVisible(false);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffProfileContent = new javax.swing.JPanel();
        editProfileLabel = new javax.swing.JLabel();
        viewSalesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Student");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        staffProfileContent.setBackground(new java.awt.Color(204, 204, 204));
        staffProfileContent.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        staffProfileContent.setPreferredSize(new java.awt.Dimension(950, 667));

        javax.swing.GroupLayout staffProfileContentLayout = new javax.swing.GroupLayout(staffProfileContent);
        staffProfileContent.setLayout(staffProfileContentLayout);
        staffProfileContentLayout.setHorizontalGroup(
            staffProfileContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        staffProfileContentLayout.setVerticalGroup(
            staffProfileContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        editProfileLabel.setBackground(new java.awt.Color(255, 153, 51));
        editProfileLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit_user_male_24px.png"))); // NOI18N
        editProfileLabel.setText("Edit Profile");
        editProfileLabel.setOpaque(true);
        editProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileLabelMouseExited(evt);
            }
        });

        viewSalesLabel.setBackground(new java.awt.Color(255, 153, 51));
        viewSalesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewSalesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewSalesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view_file_26px.png"))); // NOI18N
        viewSalesLabel.setText("View Sales");
        viewSalesLabel.setOpaque(true);
        viewSalesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSalesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewSalesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewSalesLabelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SEKARO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewSalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(editProfileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffProfileContent, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(editProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewSalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
            .addComponent(staffProfileContent, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewSalesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSalesLabelMouseClicked
        changePanelsVisibilityOnHomeScreen();
        sales.setSize(staffProfileContent.getSize());
        sales.setVisible(true);
    }//GEN-LAST:event_viewSalesLabelMouseClicked

    private void editProfileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileLabelMouseClicked
        changePanelsVisibilityOnHomeScreen();
        profile.setSize(staffProfileContent.getSize());
        profile.setVisible(true);
    }//GEN-LAST:event_editProfileLabelMouseClicked

    private void editProfileLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileLabelMouseEntered
        editProfileLabel.setBackground(new Color(255, 117, 52));
    }//GEN-LAST:event_editProfileLabelMouseEntered

    private void editProfileLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileLabelMouseExited
        editProfileLabel.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_editProfileLabelMouseExited

    private void viewSalesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSalesLabelMouseEntered
        viewSalesLabel.setBackground(new Color(255, 117, 52));
    }//GEN-LAST:event_viewSalesLabelMouseEntered

    private void viewSalesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSalesLabelMouseExited
        viewSalesLabel.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_viewSalesLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StaffProfile dialog = new StaffProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editProfileLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel staffProfileContent;
    private javax.swing.JLabel viewSalesLabel;
    // End of variables declaration//GEN-END:variables
}
